version: '3.7'

services:
  urlshortener_adminer:
    image: adminer:4.8.1
    container_name: urlshortener_adminer
    restart: unless-stopped
    ports:
      - '8088:8080'
    networks:
      - urlshortener_network
  urlshortener_db:
    image: mariadb:10.11.2
    container_name: urlshortener_db
    restart: unless-stopped
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_HOST: urlshortener_db
      MYSQL_ROOT_PASSWORD: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      MYSQL_DATABASE: urlshortener
      MYSQL_USER: urlshortener_user
      MYSQL_PASSWORD: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    volumes:
      - ./export/mysql:/var/lib/mysql
    networks:
      - urlshortener_network

  urlshortener_redis:
    container_name: urlshortener_redis
    image: redis:6.2.5
    command: redis-server --requirepass XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --appendonly yes
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./export/redis:/data
    networks:
      - urlshortener_network

networks:
  urlshortener_network:
    driver: bridge
