version: '3.7'

services:
  urlshortener_db:
    image: postgres
    environment:
      - POSTGRES_DB=url-shortener
      - POSTGRES_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXX
    volumes:
      - ./export/postgres:/data
    ports:
      - 5432:5432

  urlshortener_app:
    ports:
      - 3100:3000
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL='postgresql://postgres:XXXXXXXXXXXXXXXXXXXXXX@urlshortener_db:5432/url-shortener?schema=public'
      - NEXT_PUBLIC_URL=http://localhost:3100
      - AUTH0_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - AUTH0_BASE_URL=http://localhost:3100
      - AUTH0_ISSUER_BASE_URL=https://dev-dfeqa7nd.us.auth0.com
      - AUTH0_CLIENT_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - AUTH0_CLIENT_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
