version: '3.7'

services:
  urlshortener_db:
    image: postgres
    environment:
      - POSTGRES_DB=url-shortener
      - POSTGRES_PASSWORD=SjL2A9hc5kERsAbM
    volumes:
      - ./export/postgres:/data
    ports:
      - 5432:5432

  urlshortener_app:
    ports:
      - 3100:3000
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL='postgresql://postgres:SjL2A9hc5kERsAbM@urlshortener_db:5432/url-shortener?schema=public'
      - NEXT_PUBLIC_URL=http://localhost:3100
      - AUTH0_SECRET=4c1d446dd3db8597ab7de29edb7bb161ee76207367482618551a888500e3821f
      - AUTH0_BASE_URL=http://localhost:3100
      - AUTH0_ISSUER_BASE_URL=https://dev-dfeqa7nd.us.auth0.com
      - AUTH0_CLIENT_ID=kw9jdoSFSUBtjydV3niuHOItNfrhOcQd
      - AUTH0_CLIENT_SECRET=9amousFGD9RJppvDM_FIWXWbeBDUreISr8GpoF-Z1w8FjAdsd45qIk6vvFa9xCCF
